// Boot + system wiring. Order matters: fixed-step systems run in the order
// they appear in `fixedSystems`; render-frame systems in `frameSystems`.
import * as THREE from 'three';
import { initDebug, perfFrame, flags } from './core/debug.js';
import { loadState, game, setGameState } from './core/state.js';
import { createLoop } from './core/loop.js';
import { pollInput } from './core/input.js';
import { createRenderer } from './engine/renderer.js';
import { initSky } from './engine/sky.js';
import { createCamera } from './engine/camera.js';
import { initHUD, hudFrame } from './ui/hud.js';
import { initOverlays, loadingProgress } from './ui/overlays.js';
import { initSettings } from './ui/settings.js';
import { PAL } from './core/palette.js';

initDebug();
loadState();

const canvas = document.getElementById('gl');
const { renderer } = createRenderer(canvas);
const scene = new THREE.Scene();
const cam = createCamera();

initHUD();
initOverlays();
initSettings();

loadingProgress(0.05, 'sky…');
await initSky(scene, renderer);

loadingProgress(0.1, 'models…');
const { loadModels } = await import('./engine/assets.js');
await loadModels((f) => loadingProgress(0.1 + f * 0.5, 'models…'));

loadingProgress(0.65, 'city…');
const { buildCitySpec } = await import('./world/city.js');
const { buildStreets } = await import('./world/streets.js');
const { buildBuildings } = await import('./world/buildings.js');
const { buildProps } = await import('./world/props.js');
const city = buildCitySpec();
buildStreets(scene);
const buildingsReg = buildBuildings(scene, city.buildings);
const propsReg = buildProps(scene, city);

loadingProgress(1, 'ready');
window.__test.city = () => ({ buildings: city.buildings.length, cells: buildingsReg.cells.length, props: propsReg.all.length });
window.__test.showcase = (names) => {
  const { staticGeometry } = window.__assets;
  names.forEach((n, i) => {
    const { geometry, material } = staticGeometry(n);
    const m = new THREE.Mesh(geometry, material);
    m.position.set(-20 + i * 8, 0.02, 0);
    scene.add(m);
  });
  return names.length;
};
import('./engine/assets.js').then((m) => { window.__assets = m; });
window.__test.lookFrom = (x, y, z, tx, ty, tz) => {
  cam.st.target.set(tx, ty ?? 0, tz);
  cam.st.smoothed.set(tx, ty ?? 0, tz);
  const dx = x - tx, dz = z - tz;
  cam.st.yaw = Math.atan2(dx, dz); cam.st.curYaw = cam.st.yaw;
  const dist = Math.hypot(dx, dz);
  cam.st.pitch = Math.atan2(y - (ty ?? 0) - 1.55, dist); cam.st.curPitch = cam.st.pitch;
  cam.st.dist = Math.hypot(dx, y - (ty ?? 0), dz); cam.st.curDist = cam.st.dist;
};

if (flags.autoplay) {
  document.getElementById('title-screen').hidden = true;
  document.getElementById('hud').hidden = false;
  setGameState('playing');
}

// --- system lists (filled in over later phases)
const fixedSystems = [];
const frameSystems = [];

let simTime = 0;
function fixed(dt) {
  if (game.state !== 'playing') return;
  pollInput(dt);
  simTime += dt;
  for (const s of fixedSystems) s(dt);
}

let lastDt = 1 / 60;
function frame(dt, alpha) {
  lastDt = dt;
  if (game.state === 'playing' || game.state === 'paused') {
    for (const s of frameSystems) s(dt, alpha);
    cam.frameUpdate(dt);
    hudFrame();
  }
}

function render() {
  renderer.info.reset();
  renderer.render(scene, cam.camera);
  perfFrame(renderer, lastDt);
  window.__ready = true;
}

createLoop({ fixed, frame, render });

// expose plumbing for later phases + tests
window.__test.simTime = () => simTime;
export { scene, renderer, cam, fixedSystems, frameSystems };

// Service worker: content-hash-versioned precache, generated by tools/gen-sw.mjs
if ('serviceWorker' in navigator && location.protocol === 'https:') {
  addEventListener('load', () => {
    navigator.serviceWorker.register('./sw.js', { updateViaCache: 'none' }).catch(() => {});
  });
}
