// Boot + system wiring. Order matters: fixed-step systems run in the order
// they appear in `fixedSystems`; render-frame systems in `frameSystems`.
import * as THREE from 'three';
import { initDebug, perfFrame, flags } from './core/debug.js';
import { loadState, game, setGameState } from './core/state.js';
import { createLoop } from './core/loop.js';
import { pollInput } from './core/input.js';
import { createRenderer } from './engine/renderer.js';
import { initSky } from './engine/sky.js';
import { createCamera } from './engine/camera.js';
import { initHUD, hudFrame } from './ui/hud.js';
import { initOverlays, loadingProgress } from './ui/overlays.js';
import { initSettings } from './ui/settings.js';
import { PAL } from './core/palette.js';

initDebug();
loadState();

const canvas = document.getElementById('gl');
const { renderer } = createRenderer(canvas);
const scene = new THREE.Scene();
const cam = createCamera();

initHUD();
initOverlays();
initSettings();

loadingProgress(0.1, 'sky…');
await initSky(scene, renderer);

// P1 placeholder ground — replaced by the city in P2
const ground = new THREE.Mesh(
  new THREE.CircleGeometry(240, 48).rotateX(-Math.PI / 2),
  new THREE.MeshLambertMaterial({ color: PAL.road }),
);
scene.add(ground);

loadingProgress(1, 'ready');

if (flags.autoplay) {
  document.getElementById('title-screen').hidden = true;
  document.getElementById('hud').hidden = false;
  setGameState('playing');
}

// --- system lists (filled in over later phases)
const fixedSystems = [];
const frameSystems = [];

let simTime = 0;
function fixed(dt) {
  if (game.state !== 'playing') return;
  pollInput(dt);
  simTime += dt;
  for (const s of fixedSystems) s(dt);
}

let lastDt = 1 / 60;
function frame(dt, alpha) {
  lastDt = dt;
  if (game.state === 'playing' || game.state === 'paused') {
    for (const s of frameSystems) s(dt, alpha);
    cam.frameUpdate(dt);
    hudFrame();
  }
}

function render() {
  renderer.info.reset();
  renderer.render(scene, cam.camera);
  perfFrame(renderer, lastDt);
  window.__ready = true;
}

createLoop({ fixed, frame, render });

// expose plumbing for later phases + tests
window.__test.simTime = () => simTime;
export { scene, renderer, cam, fixedSystems, frameSystems };

// Service worker: content-hash-versioned precache, generated by tools/gen-sw.mjs
if ('serviceWorker' in navigator && location.protocol === 'https:') {
  addEventListener('load', () => {
    navigator.serviceWorker.register('./sw.js', { updateViaCache: 'none' }).catch(() => {});
  });
}
