// generated by tools/gen-sw.mjs — do not edit by hand
const VERSION = 'sm-dd8217b08b';
const NAV_TIMEOUT = 2500;
const PRECACHE = [
 "./",
 "./index.html",
 "./manifest.webmanifest",
 "./favicon.png",
 "./css/main.css",
 "./js/ai/crowd.js",
 "./js/ai/director.js",
 "./js/ai/karma.js",
 "./js/ai/monster.js",
 "./js/ai/npc.js",
 "./js/ai/panic.js",
 "./js/ai/reputation.js",
 "./js/ai/schedule.js",
 "./js/anim/locomotion.js",
 "./js/anim/poselayer.js",
 "./js/anim/poses.js",
 "./js/anim/retarget.js",
 "./js/core/debug.js",
 "./js/core/events.js",
 "./js/core/input.js",
 "./js/core/loop.js",
 "./js/core/mathx.js",
 "./js/core/palette.js",
 "./js/core/points.js",
 "./js/core/state.js",
 "./js/core/version.js",
 "./js/dialogue/bubbles.js",
 "./js/dialogue/conversation.js",
 "./js/dialogue/groq.js",
 "./js/dialogue/lines.js",
 "./js/dialogue/talk.js",
 "./js/engine/assets.js",
 "./js/engine/audio.js",
 "./js/engine/blobshadows.js",
 "./js/engine/camera.js",
 "./js/engine/citylights.js",
 "./js/engine/godrays.js",
 "./js/engine/healthpips.js",
 "./js/engine/materials.js",
 "./js/engine/particles.js",
 "./js/engine/quality.js",
 "./js/engine/renderer.js",
 "./js/engine/shadows.js",
 "./js/engine/sky.js",
 "./js/engine/tracers.js",
 "./js/engine/viewport.js",
 "./js/engine/warmup.js",
 "./js/main.js",
 "./js/physics/collide.js",
 "./js/physics/heightfield.js",
 "./js/physics/pworld.js",
 "./js/physics/spatialgrid.js",
 "./js/player/combat.js",
 "./js/player/health.js",
 "./js/player/outfit.js",
 "./js/player/player.js",
 "./js/player/weapons.js",
 "./js/ui/hud.js",
 "./js/ui/inspect.js",
 "./js/ui/overlays.js",
 "./js/ui/settings.js",
 "./js/ui/shop.js",
 "./js/world/buildings.js",
 "./js/world/city.js",
 "./js/world/debris.js",
 "./js/world/destruction.js",
 "./js/world/museum.js",
 "./js/world/procprops.js",
 "./js/world/props.js",
 "./js/world/samosa.js",
 "./js/world/streets.js",
 "./js/world/traffic.js",
 "./vendor/three/addons/libs/meshopt_decoder.module.js",
 "./vendor/three/addons/loaders/GLTFLoader.js",
 "./vendor/three/addons/utils/BufferGeometryUtils.js",
 "./vendor/three/addons/utils/SkeletonUtils.js",
 "./vendor/three/three.core.min.js",
 "./vendor/three/three.module.min.js",
 "./assets/anim/clip_die.glb",
 "./assets/anim/clip_punch.glb",
 "./assets/anim/clip_run.glb",
 "./assets/art/plaques.json",
 "./assets/art/reach.webp",
 "./assets/art/reach_512.webp",
 "./assets/art/riverbank.webp",
 "./assets/art/riverbank_512.webp",
 "./assets/art/the-reader.webp",
 "./assets/art/the-reader_512.webp",
 "./assets/art/the-visitor.webp",
 "./assets/art/the-visitor_512.webp",
 "./assets/icons/apple-touch-icon.png",
 "./assets/icons/icon-192.png",
 "./assets/icons/icon-512-maskable.png",
 "./assets/icons/icon-512.png",
 "./assets/img/splash.webp",
 "./assets/img/title.webp",
 "./assets/models/car_police.glb",
 "./assets/models/car_sedan.glb",
 "./assets/models/car_taxi.glb",
 "./assets/models/car_van.glb",
 "./assets/models/car_wreck.glb",
 "./assets/models/gun_cannon.glb",
 "./assets/models/gun_pistol.glb",
 "./assets/models/gun_rifle.glb",
 "./assets/models/gun_shotgun.glb",
 "./assets/models/gun_smg.glb",
 "./assets/models/gun_sniper.glb",
 "./assets/models/landmark_samosa.glb",
 "./assets/models/monster_a.glb",
 "./assets/models/monster_b.glb",
 "./assets/models/npc_a.glb",
 "./assets/models/npc_b.glb",
 "./assets/models/player.glb",
 "./assets/models/prop_bench.glb",
 "./assets/models/prop_dumpster.glb",
 "./assets/models/prop_hydrant.glb",
 "./assets/models/prop_kiosk.glb",
 "./assets/models/prop_sign.glb",
 "./assets/models/prop_streetlamp.glb",
 "./assets/models/prop_trafficlight.glb",
 "./assets/models/prop_tree.glb"
];

// 'reload' bypasses the HTTP cache on the way out AND refreshes it on the way
// back, so nothing here can be a stale copy of the previous deploy.
const fresh = (u) => new Request(u, { cache: 'reload' });

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(VERSION)
      .then((c) => c.addAll(PRECACHE.map(fresh)))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener('message', (e) => {
  if (e.data === 'SKIP_WAITING') self.skipWaiting();
});

// Deleting a cache a live page is still reading from is how an update breaks
// offline play. Deferred until the page that was reading it is on its way out.
let purged = false;
function purgeOldCaches() {
  if (purged) return Promise.resolve();
  purged = true;
  return caches.keys().then((keys) => Promise.all(
    keys.filter((k) => k.startsWith('sm-') && k !== VERSION).map((k) => caches.delete(k)),
  ));
}

// Keep at most ONE old cache alive — the most recent, which is the only one a
// page still on screen can be reading from. Without this a standalone PWA that
// is launched once and left running collects a 5.4 MB cache per deploy, because
// the full purge waits for a navigation that may never come. caches.keys()
// returns creation order, so the last non-current entry is the newest.
function trimOldCaches() {
  return caches.keys().then((keys) => {
    const old = keys.filter((k) => k.startsWith('sm-') && k !== VERSION);
    return Promise.all(old.slice(0, -1).map((k) => caches.delete(k)));
  });
}

self.addEventListener('activate', (e) => {
  e.waitUntil(
    self.clients.claim()
      .then(() => self.clients.matchAll({ type: 'window' }))
      // no window open: nothing is reading the old cache, so take it now
      .then((cs) => (cs.length === 0 ? purgeOldCaches() : trimOldCaches())),
  );
});

// The page shell, network-first with a timeout. Whichever answers first wins; a
// network response that lands late still refreshes the cache for next launch.
async function navigate(req) {
  const cache = await caches.open(VERSION);
  // This worker's own cache first, then any other — the fallback is what keeps a
  // page from the previous build alive while it is still on screen.
  const shell = async () => (await cache.match('./index.html'))
    || (await cache.match('./'))
    || (await caches.match('./index.html'));

  const network = fetch(fresh(req.url))
    .then((res) => {
      // A 404 or a 502 is not a page. Serving one would replace a working
      // offline shell with an error document and then cache it as the index.
      if (res && res.ok && res.type === 'basic') {
        cache.put('./index.html', res.clone()).catch(() => {});
        return res;
      }
      return null;
    })
    .catch(() => null);

  const TIMED_OUT = Symbol('timeout');
  const first = await Promise.race([
    network,
    new Promise((r) => setTimeout(() => r(TIMED_OUT), NAV_TIMEOUT)),
  ]);
  if (first && first !== TIMED_OUT) return first;

  // Slow, offline, or an error status: serve what we have.
  const cached = await shell();
  if (cached) return cached;
  // Nothing cached at all (a first visit that raced the install). The network
  // request is already in flight; wait it out rather than failing early.
  return (await network) || Response.error();
}

self.addEventListener('fetch', (e) => {
  const req = e.request;
  // Never touch a non-GET, and never touch another origin — that is what keeps
  // an opaque response out of every cache here.
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== location.origin) return;
  if (req.mode === 'navigate') {
    // A navigation means whatever was reading the previous cache is being
    // replaced; this is the moment it is safe to reclaim the space.
    e.respondWith(navigate(req));
    e.waitUntil(purgeOldCaches());
    return;
  }
  e.respondWith(
    caches.open(VERSION)
      .then((c) => c.match(req, { ignoreSearch: true }))
      // Only then any other cache: that fallback is what keeps a page from the
      // previous build alive while it is still on screen.
      .then((hit) => hit || caches.match(req, { ignoreSearch: true }))
      .then((hit) => hit || fetch(req)),
  );
});
