// generated by tools/gen-sw.mjs — do not edit by hand
const VERSION = 'sm-e3034b09ca';
const PRECACHE = [
 "./",
 "./index.html",
 "./manifest.webmanifest",
 "./favicon.png",
 "./css/main.css",
 "./js/ai/crowd.js",
 "./js/ai/director.js",
 "./js/ai/karma.js",
 "./js/ai/monster.js",
 "./js/ai/npc.js",
 "./js/ai/panic.js",
 "./js/ai/reputation.js",
 "./js/ai/schedule.js",
 "./js/anim/locomotion.js",
 "./js/anim/poselayer.js",
 "./js/anim/poses.js",
 "./js/anim/retarget.js",
 "./js/core/debug.js",
 "./js/core/events.js",
 "./js/core/input.js",
 "./js/core/loop.js",
 "./js/core/mathx.js",
 "./js/core/palette.js",
 "./js/core/state.js",
 "./js/core/version.js",
 "./js/dialogue/bubbles.js",
 "./js/dialogue/conversation.js",
 "./js/dialogue/groq.js",
 "./js/dialogue/lines.js",
 "./js/dialogue/talk.js",
 "./js/engine/assets.js",
 "./js/engine/audio.js",
 "./js/engine/blobshadows.js",
 "./js/engine/camera.js",
 "./js/engine/citylights.js",
 "./js/engine/godrays.js",
 "./js/engine/materials.js",
 "./js/engine/particles.js",
 "./js/engine/quality.js",
 "./js/engine/renderer.js",
 "./js/engine/shadows.js",
 "./js/engine/sky.js",
 "./js/engine/warmup.js",
 "./js/main.js",
 "./js/physics/collide.js",
 "./js/physics/heightfield.js",
 "./js/physics/pworld.js",
 "./js/physics/spatialgrid.js",
 "./js/player/combat.js",
 "./js/player/outfit.js",
 "./js/player/player.js",
 "./js/ui/hud.js",
 "./js/ui/overlays.js",
 "./js/ui/settings.js",
 "./js/world/buildings.js",
 "./js/world/city.js",
 "./js/world/debris.js",
 "./js/world/destruction.js",
 "./js/world/procprops.js",
 "./js/world/props.js",
 "./js/world/streets.js",
 "./js/world/traffic.js",
 "./vendor/three/addons/libs/meshopt_decoder.module.js",
 "./vendor/three/addons/loaders/GLTFLoader.js",
 "./vendor/three/addons/utils/BufferGeometryUtils.js",
 "./vendor/three/addons/utils/SkeletonUtils.js",
 "./vendor/three/three.core.min.js",
 "./vendor/three/three.module.min.js",
 "./assets/CREDITS.md",
 "./assets/anim/clip_die.glb",
 "./assets/anim/clip_punch.glb",
 "./assets/anim/clip_run.glb",
 "./assets/icons/apple-touch-icon.png",
 "./assets/icons/icon-192.png",
 "./assets/icons/icon-512-maskable.png",
 "./assets/icons/icon-512.png",
 "./assets/img/splash.webp",
 "./assets/img/title.webp",
 "./assets/models/car_police.glb",
 "./assets/models/car_sedan.glb",
 "./assets/models/car_taxi.glb",
 "./assets/models/car_van.glb",
 "./assets/models/car_wreck.glb",
 "./assets/models/gun_cannon.glb",
 "./assets/models/gun_pistol.glb",
 "./assets/models/gun_rifle.glb",
 "./assets/models/gun_shotgun.glb",
 "./assets/models/gun_smg.glb",
 "./assets/models/gun_sniper.glb",
 "./assets/models/monster_a.glb",
 "./assets/models/monster_b.glb",
 "./assets/models/npc_a.glb",
 "./assets/models/npc_b.glb",
 "./assets/models/player.glb",
 "./assets/models/prop_bench.glb",
 "./assets/models/prop_dumpster.glb",
 "./assets/models/prop_hydrant.glb",
 "./assets/models/prop_kiosk.glb",
 "./assets/models/prop_sign.glb",
 "./assets/models/prop_streetlamp.glb",
 "./assets/models/prop_trafficlight.glb",
 "./assets/models/prop_tree.glb"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('sm-') && k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (url.hostname === 'api.groq.com') return; // dialogue is always network-only
  if (url.origin !== location.origin) return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: e.request.mode === 'navigate' }).then((hit) => {
      if (hit) return hit;
      if (e.request.mode === 'navigate') {
        return caches.match('./index.html').then((page) => page || fetch(e.request));
      }
      return fetch(e.request);
    }),
  );
});
