// generated by tools/gen-sw.mjs — do not edit by hand
const VERSION = 'sm-c635889711';
const PRECACHE = [
 "./",
 "./index.html",
 "./manifest.webmanifest",
 "./favicon.png",
 "./css/main.css",
 "./js/core/debug.js",
 "./js/core/events.js",
 "./js/core/input.js",
 "./js/core/loop.js",
 "./js/core/mathx.js",
 "./js/core/palette.js",
 "./js/core/state.js",
 "./js/engine/camera.js",
 "./js/engine/renderer.js",
 "./js/engine/sky.js",
 "./js/main.js",
 "./js/ui/hud.js",
 "./js/ui/overlays.js",
 "./js/ui/settings.js",
 "./vendor/three/addons/libs/meshopt_decoder.module.js",
 "./vendor/three/addons/loaders/GLTFLoader.js",
 "./vendor/three/addons/utils/BufferGeometryUtils.js",
 "./vendor/three/addons/utils/SkeletonUtils.js",
 "./vendor/three/three.core.min.js",
 "./vendor/three/three.module.min.js",
 "./assets/anim/clip_die.glb",
 "./assets/anim/clip_punch.glb",
 "./assets/anim/clip_run.glb",
 "./assets/icons/apple-touch-icon.png",
 "./assets/icons/icon-192.png",
 "./assets/icons/icon-512-maskable.png",
 "./assets/icons/icon-512.png",
 "./assets/img/splash.webp",
 "./assets/img/title.webp",
 "./assets/models/car_sedan.glb",
 "./assets/models/car_taxi.glb",
 "./assets/models/car_van.glb",
 "./assets/models/monster_a.glb",
 "./assets/models/monster_b.glb",
 "./assets/models/npc_a.glb",
 "./assets/models/npc_b.glb",
 "./assets/models/player.glb",
 "./assets/models/prop_bench.glb",
 "./assets/models/prop_dumpster.glb",
 "./assets/models/prop_hydrant.glb",
 "./assets/models/prop_kiosk.glb",
 "./assets/models/prop_sign.glb",
 "./assets/models/prop_streetlamp.glb",
 "./assets/models/prop_trafficlight.glb",
 "./assets/models/prop_tree.glb",
 "./assets/tex/sky_equirect.webp"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('sm-') && k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (url.hostname === 'api.groq.com') return; // dialogue is always network-only
  if (url.origin !== location.origin) return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: e.request.mode === 'navigate' }).then((hit) => {
      if (hit) return hit;
      if (e.request.mode === 'navigate') {
        return caches.match('./index.html').then((page) => page || fetch(e.request));
      }
      return fetch(e.request);
    }),
  );
});
