// Generates ../sw.js: walks the site files, hashes their contents into a cache
// version, and writes a cache-first service worker with a full relative-path
// precache list. Run before any commit that changes site files.
import { createHash } from 'crypto';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, dirname, relative } from 'path';
import { fileURLToPath } from 'url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const INCLUDE = ['index.html', 'manifest.webmanifest', 'favicon.png', 'css', 'js', 'vendor', 'assets'];
// Shipped by the asset pipeline but never requested at runtime: the sky is fully
// procedural (engine/sky.js), so precaching the equirect costs every first-time
// visitor 38KB for a file the game does not open. It stays in the repo as the
// pipeline's output; it just does not belong in the offline bundle.
const EXCLUDE = ['assets/tex/sky_equirect.webp'];

const files = [];
function walk(p) {
  const st = statSync(p);
  if (st.isDirectory()) { for (const f of readdirSync(p).sort()) walk(join(p, f)); }
  else files.push(p);
}
for (const inc of INCLUDE) { try { walk(join(root, inc)); } catch { /* absent early on */ } }
const rel = (f) => relative(root, f).split('\\').join('/');
const dropped = files.filter((f) => EXCLUDE.includes(rel(f))).length;
if (dropped !== EXCLUDE.length) {
  // an EXCLUDE entry that matches nothing is a stale path, and silently keeping
  // it would hide the day someone renames the file it was meant to skip
  console.error(`gen-sw: EXCLUDE matched ${dropped} of ${EXCLUDE.length} entries`);
  process.exit(1);
}
files.splice(0, files.length, ...files.filter((f) => !EXCLUDE.includes(rel(f))));

const hash = createHash('sha256');
for (const f of files) hash.update(readFileSync(f));
const version = 'sm-' + hash.digest('hex').slice(0, 10);
const list = files.map((f) => './' + rel(f));

const sw = `// generated by tools/gen-sw.mjs — do not edit by hand
const VERSION = '${version}';
const PRECACHE = ${JSON.stringify(['./', ...list], null, 1)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('sm-') && k !== VERSION).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (url.hostname === 'api.groq.com') return; // dialogue is always network-only
  if (url.origin !== location.origin) return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: e.request.mode === 'navigate' }).then((hit) => {
      if (hit) return hit;
      if (e.request.mode === 'navigate') {
        return caches.match('./index.html').then((page) => page || fetch(e.request));
      }
      return fetch(e.request);
    }),
  );
});
`;
writeFileSync(join(root, 'sw.js'), sw);
console.log(`sw.js written: ${version}, ${list.length} precached files`);
